server:
  port: 8443
  servlet:
    context-path: /
  ssl:
    key-store-type: PKCS12
    key-store: classpath:certificates/basic.p12
    key-store-password: password
    key-alias: basic
    enabled-protocols: TLSv1.2
    enabled: true


